config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "questions#index"
  resources :questions do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  validates :title, presence: true
  validates :name, presence: true
  validates :content, presence: true, length: { minimum: 5 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # 回答の登録
  def create
    # pp params
    @question = Question.find(params[:question_id])
    @question.answers.create(answer_params)
    redirect_to question_path(@question)
  end

  # 回答の削除
  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    redirect_to @question, status: :see_other
  end

  private

  def answer_params
    params.require(:answer).permit(:name, :content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # 質問一覧表示
  def index
    @questions = Question.all
    # pp @questions
  end

  # 質問詳細ページ表示
  def show
    # p params[:id]
    @question = Question.find(params[:id])
    # pp @question
  end

  # 質問の作成
  def new
    @question = Question.new
  end

  # 質問の編集
  def edit
    @question = Question.find(params[:id])
  end

  # 質問の登録
  def create
    # Questionモデルの初期化
    @question = Question.new(question_params)
    # QuestionモデルをDBへ保存
    if @question.save
      # showへリダイレクト
      redirect_to @question
    else
      # pp @question
      render 'new', status: :unprocessable_entity
    end
  end

  # 質問の更新
  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  # 質問の削除
  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :name, :content)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qanda</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- <main class="container mx-auto mt-28 px-5 flex"> -->
      <%= yield %>
    <!-- </main> -->
  </body>
</html>

app/views/questions/_form.html.erb
<div class="w-100vh">
    <%= form_with model: @question do |form| %>
    <% if @question.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded" role="alert">
        <h2 class="font-bold text-3xl mb-2"><%= pluralize(@question.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
            <% @question.errors.each do |error|  %>
                <li><%= error.full_message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>
       <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 flex-col">
            <div class="mb-6">
                <%= form.label :title, class: "block text-gray-700 text-xl font-bold mb-2" %>
                <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
            </div>
            <div class="mb-6">
                <%= form.label :name, class: "block text-gray-700 text-xl font-bold mb-2" %>
                <%= form.text_field :name, class: "shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" %>
            </div>
            <div class="mb-6">
                <%= form.label :content, class: "block text-gray-700 text-xl font-bold mb-2" %>
                <%= form.text_area :content, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
            </div>
            <div class="flex justify-center items-center">
                <button class="mb-6 bg-blue-500 hover:bg-blue-700 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                    <%= form.submit "投稿", class: "text-white" %>
                 </button>
            </div>
       </div>
    <% end %>
</div>

app/views/questions/edit.html.erb
<div class="flex w-100vh justify-center items-center pt-4 mb-4">
    <h1 class="text-4xl font-bold">Edit Question</h1>
</div>

<%= render partial: 'form' %>

app/views/questions/index.html.erb
<div class="flex w-100vh justify-center items-center pt-4 mb-4">
    <h1 class="text-4xl font-bold">All Questions</h1>
</div>

<div class="flex justify-center items-center pt-4 mt-4">
    <%= link_to 'create', new_question_path, class: "font-medium text-xl bg-blue-500 text-white dark:text-white hover:underline hover:bg-blue-700 rounded-md p-2"  %>
</div>

<div class="flex w-100vh justify-center items-center pt-4 mb-4 relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">ID</th>
                <th scope="col" class="px-6 py-3">Title</th>
                <th scope="col" class="px-6 py-3">Name</th>
                <th scope="col" class="px-6 py-3">Content</th>
                <th scope="col" class="px-6 py-3">CreatedAt</th>
                <th scope="col" class="px-6 py-3">UpdatedAt</th>
                <th scope="col" class="px-6 py-3">Show</th>
                <th scope="col" class="px-6 py-3">Edit</th>
                <th scope="col" class="px-6 py-3">Delete</th>
            </tr>
        </thead>
        
        <tbody>
            <% @questions.map do |question| %>
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                <td class="px-6 py-4"><%= question.id %></td>
                <td class="px-6 py-4"><%= question.title %></td>
                <td class="px-6 py-4"><%= question.name %></td>
                <td class="px-6 py-4"><%= question.content %></td>
                <td class="px-6 py-4"><%= l question.created_at %></td>
                <td class="px-6 py-4"><%= l question.updated_at %></td>
                <td class="px-6 py-4"><%= link_to 'show', question_path(question), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline"  %></td>
                <td class="px-6 py-4"><%= link_to 'edit', edit_question_path(question), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline"  %></td>
                <td class="px-6 py-4"><%= link_to 'destroy', question_path(question), data: {turbo_method: 'delete', turbo_confirm: 'Are you sure?'}, class: "font-medium text-blue-600 dark:text-blue-500 hover:underline"  %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/questions/new.html.erb
<div class="flex w-100vh justify-center items-center pt-4 mb-4">
    <h1 class="text-4xl font-bold">New Question</h1>
</div>
    
<%= render partial: 'form' %>

app/views/questions/show.html.erb
<div class="flex w-100vh justify-center items-center pt-4 mb-4">
    <h1 class="text-4xl font-bold">Show Question</h1>
</div>

<div class="flex justify-around items-center mt-2 mb-4">
    <div>
        <h2 class="text-4xl font-bold">Title: <%= @question.title %></h2>
    </div>
    <div>
        <p class="text-2xl">Name: <%= @question.name %></p>
    </div>
</div>

<div class="flex justify-center items-center mb-4 pt-2">
    <div>
        <p>Content: <%= @question.content %></p>
    </div>
</div>

<div>
    <div class="flex w-100vh justify-center items-center pt-4 mb-2">
        <h1 class="text-4xl font-bold">Answers</h1>
    </div>
    <% @question.answers.each do |answer| %>
        <div class="flex justify-center items-center mt-2 mb-2 pt-2 py-2">
            <p class="text-xl font-bold">
                Name: <%= answer.name %>
            </p>
        </div>
        <div class="flex justify-center items-center mt-2 mb-2 pt-2 py-2">
            <p class="text-xl font-bold">
                Content: <%= answer.content %>
            </p>
        </div>

        <div class="flex justify-center items-center mt-2 mb-2 pt-2 py-2">
            <p>
                <%= link_to 'Delete Answer', [answer.question, answer], data: {turbo_method: 'delete', turbo_confirm: 'Are you sure?'}, class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
            </p>
        </div>
    <% end %>
</div>

<div>
    <div class="flex w-100vh justify-center items-center pt-4 mb-2">
        <h1 class="text-4xl font-bold">Add a Answer</h1>
    </div>
    
    <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 flex-col">
        <%= form_with model: [@question, @question.answers.build] do |form| %>
        <div class="mb-6">
            <%= form.label :name, class: "block text-gray-700 text-xl font-bold mb-2" %>
            <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>
        <div class="mb-6">
            <%= form.label :content, class: "block text-gray-700 text-xl font-bold mb-2" %>
            <%= form.text_area :content, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>
        <div class="flex justify-center items-center">
            <button class="mb-6 bg-blue-500 hover:bg-blue-700 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                <%= form.submit "投稿", class: "text-white" %>
             </button>
        </div>
    <% end %>
    </div>
</div>

<div class="flex justify-center items-center pt-4 mt-4 pb-4 mb-4">
    <%= link_to 'top', questions_path, class: "font-medium text-xl bg-blue-500 text-white dark:text-white hover:underline hover:bg-blue-700 rounded-md p-2" %>
</div>